dist: trusty
sudo: false
language : node_js
services: 
  - mongodb
node_js:
  - "6"
cache:
  directories:
    - node_modules
    - bower_components
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - npm run update-webdriver
script:
  - grunt test
  - grunt test:e2e
  - grunt build
