dist: trusty
sudo: false
language : node_js
services: 
  - mongodb
node_js:
  - "6"
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - npm run update-webdriver
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16"
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
script:
  - grunt test
  - grunt test:e2e
  - grunt build
