dist: trusty
sudo: false
language: node_js
services:
- mongodb
node_js:
- '6'
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- openssl aes-256-cbc -K $encrypted_e768e08fceaf_key -iv $encrypted_e768e08fceaf_iv
  -in github_rsa.enc -out ~\/.ssh/github_rsa -d
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower grunt-cli
- bower install
- npm run update-webdriver
script:
- grunt test
- grunt test:e2e
- grunt build
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
  - grunt buildcontrol:deploy
  - grunt buildcontrol:pages
