dist: trusty
sudo: false
language : node_js
node_js:
  - "6"
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - npm run update-webdriver
script:
  - grunt test
  - grunt test:e2e
  - grunt build
